### PR TITLE
Add error handling to publish callback, fix target branch

### PR DESCRIPTION
**Pull request by kyleratti**
This should reveal any errors that occur when trying to publish the `public` folder

### CODE REVIEW

**Comment by kyleratti** [comment]
As discussed on https://github.com/tschaub/gh-pages/issues/351, you want `master` to be the generated site files and `develop` to be your code, so I added a commit to fix the target deployment branch.

**Comment by Bam92** [comment]
My real need is that `develop` be the generated site.

**Comment by kyleratti** [comment]
So to clarify, you want:

`master` branch = source code
`develop` branch = compiled HTML/CSS/JS to be served on GitHub Pages

Is that correct?

**Comment by Bam92** [comment]
Let me explain a bit more the context so that you can suggest me something good.

I usually follow the `gitflow` work flow: `master` for `release` and `develop` for development. In this project master goes to `netlify`. `develop` branch is for test before the next release. 

What do you think would be good in this context, add a `gh-pages` branch?

**Comment by kyleratti** [comment]
I think I'm with you now - you are wanting to publish the source to `develop` but have GitHub Pages host the build version of the `develop` source code?

If so, you'd want to publish to another branch; something like `gh-pages` would do, but a more descriptive name might make more sense at a glance (like `develop-gh-pages` or `develop-public` maybe.)

**Comment by Bam92** [comment]
You really get it. So I create `develop-public` and configure `gh-pages` to use it?

**Comment by kyleratti** [comment]
Yes sir - you would create `develop-public` and set GitHub Pages to use that branch in your repository settings. Then you'd have the following branches:

- `master`: Source code for production/netlify
- `develop`: Source code for development
- `develop-public` - Compiled HTML/CSS/JS app code used by GitHub Pages

**Comment by kyleratti** [comment]
I modified your script on this pull request to reflect using the `develop-public` branch

**Comment by Bam92** [comment]
Just one more question: do I have to push my `public` folder or it is Ok to stay in `.gitignore`?

**Comment by kyleratti** [comment]
You would leave it in .gitignore. If you remove it, you will end up committing the folder to your `develop` branch (along side your source doe) in addition to publishing just the compiled code to `develop-public` via your script.

There's nothing technically wrong with that but from a personal standpoint I would leave `public/` in `.gitignore` as I like to keep the source code completely separate from the build code.

**Comment by Bam92** [comment]
I tried to push, I'm getting an error 
```
info bootstrap finished - 15.713 s
⠀
success Building production JavaScript and CSS bundles - 11.447s
success run queries - 11.780s - 1/1 0.08/s
success Building static HTML for pages - 2.602s - 2/2 0.77/s
success onPostBuild - 0.001s
info Done building in 30.166760156 sec
ProcessError: fatal: A branch named 'develop-public' already exists.

    at ChildProcess.<anonymous> (/home/abelmbula/Documents/my-blog/node_modules/gh-pages/lib/git.js:42:16)
    at ChildProcess.emit (events.js:219:5)
    at maybeClose (internal/child_process.js:1027:16)
    at Socket.<anonymous> (internal/child_process.js:442:11)
    at Socket.emit (events.js:219:5)
    at Pipe.<anonymous> (net.js:666:12) {
  code: 128,
  message: "fatal: A branch named 'develop-public' already exists.\n",
  name: 'ProcessError'
}

```

**Comment by Bam92** [comment]
Github Pages has a limited number of source branches: `master` and `gh-pages`. It's not possible to use `develop-public`.

**Comment by kyleratti** [comment]
@Bam92 I apologize, you are 100% correct. We would need to use `gh-pages` instead of `develop-public`.

**Comment by kyleratti** [comment]
In regards to your push error, see this tip for resolving: https://www.npmjs.com/package/gh-pages#tips

**Pull request merged**
